version: "3"

services:
  express_server:
    image: jiajidev/express-server-sample:${IMAGE_VERSION}
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=dbuser
      - DB_PASS=dbpass
      - DB_DB=hotel
    network_mode: host

