version: "3"
services:
  mysql:
    image: "mysql:5.7.34"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=hotel
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ../mysql/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
      - ../mysql/scripts/:/docker-entrypoint-initdb.d/
  express_server:
    image: jiajidev/express-server-sample:0.2
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=dbuser
      - DB_PASS=dbpass
      - DB_DB=hotel
      - WAIT_HOSTS=mysql:3306
    