version: "3"
services:
  mysql:
    image: "mysql:5.7.34"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=hotel
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ../mysql/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
      - ../mysql/scripts/:/docker-entrypoint-initdb.d/
